typography_spectrum: 0.3980223585385829
color:
  brandStrength: 0.17087482358328998
  lightness: 0.8581030429340899
  saturation: 0.4685087203979492
  rhythmicContrast: 0.3967140060849488
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.1671846138779074
author:
  name: 'Arno Fischbacher '
  email: arno.fischbacher@stimme.at
  url: 'http://www.arno-fischbacher.com '
name: Stimme wirkt. Voice sells!
navigation:
  - name: Stimme
    url: 'http://www.arno-fischbacher.com '
    type: external
title: Stimme hat Macht.
description: 'Wer sie nutzt, ist klar im Vorteil.'
